version: '2'

services:
  ca.example.com:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/home/ran/agricultural-supply-chain
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/home/ran/agricultural-supply-chain/peer0.org1.example.com.crt
      - FABRIC_CA_SERVER_CA_KEYFILE=/home/ran/agricultural-supply-chain/peer0.org1.example.com.key
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.2
    container_name: orderer.example.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    volumes:
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
      - ./crypto-config:/etc/hyperledger/crypto-config
    ports:
      - 7050:7050
    networks:
      - basic

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.2
    container_name: peer0.org1.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/etc/hyperledger/crypto-config
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
    ports:
      - 7051:7051
    networks:
      - basic

  cli:
    image: hyperledger/fabric-tools:2.2
    container_name: cli
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/etc/hyperledger/crypto-config
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../chaincode:/opt/gopath/src/supplychain
    networks:
      - basic

networks:
  basic:
    driver: bridge
